from pathlib import Path

SAMPLE_RATE = 16000
N_MELS = 80
N_FFT = 400
HOP_LENGTH = 160
F_MIN = 80
F_MAX = 8000
MEL_SCALE = "linear"


LATENT_DIM = 16
HIDDEN_DIM = 256
NUM_RES_BLOCKS = 2

NUM_EMBEDDINGS = 4096
EMBEDDING_DIM = 16
VQ_DECAY = 0.99
VQ_EPSILON = 1e-5

TIMESTEPS = 1000
BASE_CHANNELS = 64
DIFFUSION_TIME_EMB_DIM = 128
DIFFUSION_DROPOUT = 0.1

BETA_START = 1e-4
BETA_END = 0.02

COMPRESSION_LR = 1e-3
VQ_WEIGHT = 0.25
PERCEPTUAL_WEIGHT = 0.5
COMPRESSION_EPOCHS = 50
COMPRESSION_BATCH_SIZE = 4

DIFFUSION_LR = 1e-4
DIFFUSION_EPOCHS = 50
DIFFUSION_BATCH_SIZE = 4

HYBRID_LR = 1e-3
HYBRID_EPOCHS = 50
HYBRID_BATCH_SIZE = 4

OPTIMIZER = "adam"
SCHEDULER = "step"
SCHEDULER_STEP_SIZE = 10
SCHEDULER_GAMMA = 0.5

DATA_DIR = Path("data")
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
PROCESSED_NORM_DATA_DIR = DATA_DIR / "processed_norm"

TEST_SPEAKER = "1995"
TEST_CHAPTER = "1826"
TEST_DATA_DIR = PROCESSED_NORM_DATA_DIR / "test-clean" / TEST_SPEAKER / TEST_CHAPTER
NUM_TEST_SAMPLES = 10

EVAL_BITRATE_TARGET = (8, 16)
EVAL_LATENCY_TARGET = 20
EVAL_PESQ_TARGET = 3.5
EVAL_STOI_TARGET = 0.9

CHECKPOINT_DIR = Path("lightning_logs")
EVAL_OUTPUT_DIR = Path("eval_outputs")
PLOTS_DIR = Path("plots")

COMPRESSION_CHECKPOINT = "compression_codec_best.ckpt"
DIFFUSION_CHECKPOINT = "diffusion_codec_best.ckpt"
HYBRID_CHECKPOINT = "hybrid_codec_best.ckpt"

USE_GPU = True
NUM_WORKERS = 4


LOG_INTERVAL = 100
VAL_CHECK_INTERVAL = 0.5
SAVE_TOP_K = 3
MONITOR_METRIC = "val_loss"
MONITOR_MODE = "min"

VOCODER_TYPE = "hifigan"
VOCODER_CHECKPOINT = None
VOCODER_REQUIRES_LOG_MEL = True

PRECOMPUTE_FEATURES = True
FEATURES_CACHE_DIR = DATA_DIR / "features_cache"

DEBUG_MODE = False
DEBUG_BATCH_SIZE = 2

USE_MIXED_PRECISION = True
PRECISION = "16-mixed"

GRADIENT_CLIP_VAL = 1.0
GRADIENT_CLIP_ALGORITHM = "norm"
SEED = 42
