from pathlib import Path

SAMPLE_RATE = 16000
N_MELS = 80
N_FFT = 1024
HOP_LENGTH = 256
F_MIN = 0
F_MAX = 8000
MEL_SCALE = "linear"


LATENT_DIM = 64
HIDDEN_DIM = 256
NUM_RES_BLOCKS = 4

NUM_EMBEDDINGS = 8192
EMBEDDING_DIM = 64
VQ_DECAY = 0.99
VQ_EPSILON = 1e-5

TIMESTEPS = 1000
BASE_CHANNELS = 64
DIFFUSION_TIME_EMB_DIM = 128
DIFFUSION_DROPOUT = 0.1

BETA_START = 1e-4
BETA_END = 0.02

LR = 1e-4
VQ_WEIGHT = 0.25
PERCEPTUAL_WEIGHT = 0.5
TRAIN_EPOCHS = 50
TRAIN_BATCH_SIZE = 4

OPTIMIZER = "adam"
OPTIMIZER = "adamw"
SCHEDULER = "cosine"
SCHEDULER_STEP_SIZE = 10
SCHEDULER_GAMMA = 0.5

VALIDATION_WAVEFORM_METRICS = True

VQ_NUM_EMBEDDINGS = NUM_EMBEDDINGS
VQ_EMBEDDING_DIM = EMBEDDING_DIM
LATENT_SPATIAL_SCALE = 1

DATA_DIR = Path("data")
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
PROCESSED_NORM_DATA_DIR = DATA_DIR / "processed_norm"

TEST_SPEAKER = "1995"
TEST_CHAPTER = "1826"
TEST_DATA_DIR = PROCESSED_NORM_DATA_DIR / "test-clean" / TEST_SPEAKER / TEST_CHAPTER
NUM_TEST_SAMPLES = 10

EVAL_BITRATE_TARGET = (8, 16)
EVAL_LATENCY_TARGET = 20
EVAL_PESQ_TARGET = 3.5
EVAL_STOI_TARGET = 0.9

CHECKPOINT_DIR = Path("lightning_logs")
EVAL_OUTPUT_DIR = Path("eval_outputs")
PLOTS_DIR = Path("plots")

USE_GPU = True
NUM_WORKERS = 4
LOG_INTERVAL = 100
VAL_CHECK_INTERVAL = 0.5
SAVE_TOP_K = 3
MONITOR_METRIC = "val_loss"
MONITOR_MODE = "min"

VOCODER_TYPE = "hifigan"
VOCODER_CHECKPOINT = None
VOCODER_REQUIRES_LOG_MEL = True

PRECOMPUTE_FEATURES = True
FEATURES_CACHE_DIR = DATA_DIR / "features_cache"

DEBUG_MODE = False
DEBUG_BATCH_SIZE = 2

USE_MIXED_PRECISION = True
PRECISION = "32"

GRADIENT_CLIP_VAL = 1.0
GRADIENT_CLIP_ALGORITHM = "norm"
SEED = 42

ENABLE_EARLY_STOPPING = True
EARLY_STOPPING_MONITOR = MONITOR_METRIC
EARLY_STOPPING_MODE = MONITOR_MODE
EARLY_STOPPING_PATIENCE = 5
EARLY_STOPPING_MIN_DELTA = 1e-4
